### PR TITLE
add compiler to the runtime deps

### PR DESCRIPTION
**Pull request by bgruening**
Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

We do the same for r-base. This makes it easier for bundler or gems to be built.

### CODE REVIEW

**Comment by jakirkham** [comment]
Admittedly we could say the same thing about Python or other languages that sometimes build C extensions when installing certain packages. Should we always add the compilers to them? Personally would prefer we document how users handle this should they need it. Better still if we build out binary gems so this isn't needed. 😉

**Comment by scopatz** [comment]
I agree with @jakirkham

**Comment by phil-blain** [comment]
@jakirkham how do you suggest we document this ?

One idea is to use `$PREFIX/.messages.txt` so that upon installing the `ruby` package, we output a message like

```
To install gems with native extensions, you need the conda-forge compilers in your environment.

Provided the conda-forge channel is properly configured with strict priority, you can install the compilers with:
    
    conda install compilers
```

That would be the easiest way at the moment, I think. But then this message is automatically removed by conda after installation is finished, so it's not that great because users have no easy way to see this message again.

What would be easier is if conda had a `conda info <package>` command, like Homebrew does (which shows the "Caveats" section that are also shown at the end of installation).

Another idea is to mention it in the README of the feedstock, but this has a lot less visibility for users.

**Comment by phil-blain** [comment]
@wolfv did it get documented ? (Why are you closing this now?)

**Comment by wolfv** [comment]
can you open an issue instead? I don't think we're going to merge this PR as outlined above.

**Comment by phil-blain** [comment]
Yes, sure!

**Comment by phil-blain** [comment]
@wolfv I just opened #44

**Comment by wolfv** [comment]
great! btw if you have input on https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/917 please let me know :)

**Comment by phil-blain** [comment]
oh, sorry I can't be of much help there. I really don't know a thing about Ruby. I just had a rough experience installing Ruby form conda-forge to locally build some websites I was contributing to, so that's why I commented on a few issues/PRs here :)

**Pull request closed without merging**
