### PR TITLE
Update to 2.5.5

### PR DESCRIPTION
**Pull request by sodre**
Trying 2.5.5, to check if it works for osx

### CODE REVIEW

**Comment by sodre** [comment]
@conda-forge-admin, please rerender

**Comment by sodre** [comment]
@conda-forge/ruby Ruby 2.5.5 is ready for review/merge. I am working on 2.6.x series next.

**Comment by scopatz** [comment]
I think the build number needs to be dropped to zero, right?

**Comment by sodre** [comment]
@scopatz, you're right! I forgot to do it on the 2.5.x branch.

**Comment by sodre** [comment]
Ruby 2.5.5 is ready for review/merge.

**Pull request merged**
