### PR TITLE
For ruby-2.3.3

### PR DESCRIPTION
**Pull request by abhi18av**
The discussion thread for this PR was initiated in https://github.com/conda-forge/ruby-feedstock/issues/1

### CODE REVIEW

**Comment by abhi18av** [comment]
This statement in the ReadMe.md is a bit unclear to me 


```
 Note that all branches in the conda-forge/ruby-feedstock are immediately built and any created packages are uploaded, so PRs should be based on branches in forks and branches in the main repository should only be used to build distinct package versions.

```

**Comment by abhi18av** [comment]
Please let me know if I need to push this as a branch instead.

**Comment by scopatz** [comment]
Thanks!

**Comment by abhi18av** [comment]
My pleasure @scopatz

**Pull request merged**
