### PR TITLE
Ruby 2.4.2 meta

### PR DESCRIPTION
**Pull request by jimmynguyc**
Fixes https://github.com/conda-forge/ruby-feedstock/issues/3

### CODE REVIEW

**Comment by jakirkham** [comment]
Could add yourself as a maintainer if you would like. If you choose to, would push another commit adding your GitHub username to the `extra/recipe-maintainers` list. Can add `[ci skip]` to that commit message since there's no need to run CI again for such a change.

**Comment by jimmynguyc** [comment]
Done :)

**Comment by jakirkham** [comment]
Would appreciate a review @scopatz (if you have time of course). :)

**Comment by scopatz** [comment]
LGTM thanks!

**Pull request merged**
