### PR TITLE
Fixup zsh detection

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Avoids unbounded variable error

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
See https://github.com/mamba-org/mamba/pull/1440

**Review by xhochy — APPROVED** [review]

**Comment by wolfv** [comment]
the windows issue looks unrelated. Let's try again in a few hours.

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
This should now be ready @wolfv @xhochy :)

**Comment by wolfv** [comment]
Thanks! Completely missed the rerender

**Pull request merged**
