### PR TITLE
ARM OSX Migrator fix (for master branch / #60)

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
This is ready for review/merge. Many thanks @isuruf for your tips! Once this PR is merged, I'm happy to create similar ones for the other branches.

**Comment by isuruf** [comment]
Do you need older ruby versions? If not, I suggest going only with the latest?

**Comment by Tobias-Fischer** [comment]
Good point, agreed. We only need the latest one :)

**Comment by Tobias-Fischer** [comment]
Ping @conda-forge/ruby

**Pull request merged**
