### PR TITLE
Enable fiddle extension also on Windows

### PR DESCRIPTION
**Pull request by traversaro**
Required by https://github.com/conda-forge/libignition-tools-feedstock/pull/12#issuecomment-954826254 . As the fiddle extentions is using `libffi` that is found by the custom build script via `pkg-config`, this PR enables the `libffi` and `pkg-config` dependencies also on Windows.

Tests have been added to ensure that the `fiddle` extention indeed loads fine.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
The PR is ready for review @conda-forge/ruby @wolfv . This should unblock https://github.com/conda-forge/libignition-tools-feedstock/pull/12#issuecomment-954826254 .

**Comment by Tobias-Fischer** [comment]
Any chance of merging this in @conda-forge/ruby @wolfv?

**Comment by traversaro** [comment]
And after all this time, I just realized that I forgot to bump the build number. -_-

**Comment by traversaro** [comment]
> And after all this time, I just realized that I forgot to bump the build number. -_-

New PR in https://github.com/conda-forge/ruby-feedstock/pull/86 .

**Pull request merged**
