### PR TITLE
Fix #116: set correct symlink for ruby in rubygems/bin/ dir

### LINKED ISSUE #116: Add symlink to $PREFIX/share/rubygems/bin/ruby
I've sucessfully installed `github_changelog_generator` as a gem, but then it complained about missing `share/rubygems/bin/ruby`:

```
(base) ➜  mamba git:(main) ✗ github_changelog_generator
/Users/wolfvollprecht/micromamba/share/rubygems/bin/github_changelog_generator: line 6: /Users/wolfvollprecht/micromamba/share/rubygems/bin/ruby: No such file or directory
/Users/wolfvollprecht/micromamba/share/rubygems/bin/github_changelog_generator: line 6: exec: /Users/wolfvollprecht/micromamba/share/rubygems/bin/ruby: cannot execute: No such file or directory
```

I was able to fix it by running:

```
ln -s ~/micromamba/bin/ruby /Users/wolfvollprecht/micromamba/share/rubygems/bin/ruby
```

### PR DESCRIPTION
**Pull request by sdruskat**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)

Hope I've done this in the correct place, `recipe/meta.yaml`?

* [x] ~~Reset the build number to `0` (if the version changed)~~
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged. _(unsure how to do this, see [this comment](https://github.com/conda-forge/ruby-feedstock/pull/130#issuecomment-2267045748))_

Fixes #116

Builds on #122, which set the symlink in the wrong place; simply fixes the creation of the symlink in the right place.

### CODE REVIEW

**Comment by sdruskat** [comment]
@conda-forge-admin, please rerender

**Comment by sdruskat** [comment]
As a newbie, I'm guessing that checking that the license file is being packaged can be done only once the jobs are run, by manually checking the artifacts?

**Comment by sdruskat** [comment]
The currently failing pipelines are all due to errors in the conda builds, e.g.:

```
conda.CondaMultiError: Conda detected a mismatch between the expected content and downloaded content
for url 'https://conda.anaconda.org/conda-forge/noarch/libstdcxx-devel_linux-aarch64-12.4.0-h7b3af7c_100.conda'.
  download saved to: /home/conda/feedstock_root/build_artifacts/pkg_cache/libstdcxx-devel_linux-aarch64-12.4.0-h7b3af7c_100.conda
  expected sha256: b9f13fa1fde239832c0ed6dbf065252284c2b99b07274f8f7b3da658f52c99ec
```

I'm not sure how to fix this. Can anybody help?

**Comment by sdruskat** [comment]
@conda-forge-admin, please rerender

**Comment by wolfv** [comment]
Thanks for working on this. I just re-ran the failed checks.

**Comment by sdruskat** [comment]
@wolfv Seeing that the Docker builds still fail, I'm wondering whether installing Ruby 3.2.* during build was an issue. Set to 3.3.* in 31a50773525cb7ce9aa73ead70b863ecf9bf9f13 to see if that fixes the issues.

**Comment by wolfv** [comment]
@conda-forge-admin restart ci

**Comment by wolfv** [comment]
@conda-forge-admin rerender

**Comment by wolfv** [comment]
@conda-forge-admin rerender

**Comment by wolfv** [comment]
@iandol I'll try to get this one in today :)

**Comment by wolfv** [comment]
Fixed this in a separate PR.

**Comment by sdruskat** [comment]
> Fixed this in a separate PR.

Great, thanks @wolfv!

**Pull request merged**
